CompileFlags:
    Add: [
        -isystem,
        /usr/include/c++/v1,
        -isystem,
        /usr/include/c++/v1/backward,
        -isystem,
        /usr/local/include,
        -isystem,
        /usr/include,
    ]
